export default [
    {
        _id: "10",
        quizId: "1", // each question belongs to a specific quiz that has the specified quizId
        questionType: "Multiple Choice",
        title: "Question 1",
        points: 1,
        content: "What Japanese automaker is known for using horizontally opposed engines?",
        answer: ["Subaru"],
        options: ["Toyota", "Suzuki", "Subaru", "Mitsubishi"],
        selectedOption: '',
        numOptions: 4,
    },

    {
        _id: "20",
        quizId: "1",
        questionType: "True/False",
        title: "Question 2",
        points: 1,
        content: "Rockets have no aerodynamic properties to them.",
        answer: ["False"],
        options: ["True", "False"],
        selectedOption: '',
        numOptions: 2,
    },
    {
        _id: "30",
        quizId: "2",
        questionType: "Fill In The Blank",
        title: "Question 1",
        points: 1,
        content: "What is the capitol of California",
        answer: ["Sacramento"],
        options: [],
        selectedOption: '',
        numOptions: 1,
    },
    {
        _id: "40",
        quizId: "2",
        questionType: "Multiple Choice",
        title: "Question 2",
        points: 1,
        content: "Who is currently the only and first ever Chinese driver in Formula 1?",
        answer: ["Zhou Guanyu"],
        options: ["Daniel Ricciardo", "Ayrton Senna", "Yuki Tsunoda", "Zhou Guanyu"],
        selectedOption: '',
        numOptions: 4,
    },
    {
        _id: "50",
        quizId: "2",
        questionType: "True/False",
        title: "Question 3",
        points: 1,
        content: "There are 300 days in a year.",
        answer: ["False"],
        options: ["True", "False"],
        selectedOption: '',
        numOptions: 4,
    },
    {
        _id: "60",
        quizId: "3",
        questionType: "True/False",
        title: "Question 1",
        points: 1,
        content: "Rockets have aerodynamic properties",
        answer: ["True"],
        options: ["True", "False"],
        selectedOption: '',
        numOptions: 2,
    },
    {
        _id: "70",
        quizId: "3",
        questionType: "Multiple Choice",
        title: "Question 2",
        points: 1,
        content: "Which of the following companies sell cars?",
        answer: ["Toyota"],
        options: ["Nike", "Puma", "Rockstar Games", "Toyota"],
        selectedOption: '',
        numOptions: 4,
    },
    {
        _id: "80",
        quizId: "4",
        questionType: "Fill In The Blank",
        title: "Question 1",
        points: 1,
        content: "What state is Boston in?",
        answer: ["Massachusetts"],
        options: [],
        selectedOption: '',
        numOptions: 1,
    },
    {
        _id: "90",
        quizId: "4", 
        questionType: "True/False",
        title: "Question 2",
        points: 1,
        content: "Northeastern University is located in Ohio.",
        answer: ["False"],
        options: ["True", "False"],
        selectedOption: '',
        numOptions: 2,
    },
]