export default [
    {
        "_id": "1",
        "course": "RS101",
        "title": "Q1 - Introduction to Rockets",
        "quizType": "Graded Quiz",
        "points": 20,
        "group": "Quizzes",
        "shuffled": true,
        "multipleAttempts": false,
        "showCorrect": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "requireLockdownBroswer": false,
        "requireViewQuizResults": false,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-04-15T23:59:59Z",
        "availableDate": "2024-04-10T00:00:00Z",
        "untilDate": "2024-04-20T23:59:59Z",
        "published": false,
    },
    {
        "_id": "2",
        "course": "RS101",
        "title": "Q2 - Freebie",
        "quizType": "Graded Quiz",
        "points": 100,
        "group": "Quizzes",
        "shuffled": true,
        "multipleAttempts": false,
        "showCorrect": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "requireLockdownBroswer": false,
        "requireViewQuizResults": false,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-03-15T23:59:59Z",
        "availableDate": "2024-03-10T00:00:00Z",
        "untilDate": "2024-03-20T23:59:59Z",
        "published": false,
    },
    {
        "_id": "3",
        "course": "RS102",
        "title": "Q1 - Fundamentals of Aerodynamics",
        "quizType": "Graded Quiz",
        "points": 100,
        "group": "Quizzes",
        "shuffled": true,
        "multipleAttempts": false,
        "showCorrect": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "requireLockdownBroswer": false,
        "requireViewQuizResults": false,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-02-15T23:59:59Z",
        "availableDate": "2024-02-10T00:00:00Z",
        "untilDate": "2024-02-20T23:59:59Z",
        "published": false,
    },
    {
        "_id": "4",
        "course": "RS102", // each quiz belongs to a specific course
        "title": "Q2 - Subsonic and Supersonic Flow",
        "quizType": "Graded Quiz",
        "points": 100,
        "group": "Quizzes",
        "shuffled": true,
        "multipleAttempts": false,
        "showCorrect": false,
        "accessCode": "",
        "oneQuestionAtATime": true,
        "requireLockdownBroswer": false,
        "requireViewQuizResults": false,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "dueDate": "2024-01-15T23:59:59Z",
        "availableDate": "2024-01-10T00:00:00Z",
        "untilDate": "2024-01-20T23:59:59Z",
        "published": false,
    }
]